# Generated by Django 5.2.3 on 2025-06-24 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_product_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
